export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SHOW_MESSAGE = "SHOW_MESSAGE";

//GET USER DETAILS TYPE
export const GET_USER_DETAILS_START = "GET_USER_DETAILS_START";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";

//GET ALL USERS
export const GET_ALL_USERS_START = "GET_ALL_USERS_START";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";

//EDIT USER DETAILS TYPE
export const EDIT_USER_DETAILS_START = "EDIT_USER_DETAILS_START";
export const EDIT_USER_DETAILS_FAILURE = "EDIT_USER_DETAILS_FAILURE";
export const EDIT_USER_DETAILS_SUCCESS = "EDIT_USER_DETAILS_SUCCESS";

//ADD USER ACTION TYPE
export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";

//CREATE COURSE ACTION TYPE
export const CREATE_COURSE_START = "CREATE_COURSE_START";
export const CREATE_COURSE_FAILURE = "CREATE_COURSE_FAILURE";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";

//GET COURSE LIST ACTION TYPE
export const GET_COURSE_LIST_START = "GET_COURSE_LIST_START";
export const GET_COURSE_LIST_FAILURE = "GET_COURSE_LIST_FAILURE";
export const GET_COURSE_LIST_SUCCESS = "GET_COURSE_LIST_SUCCESS";

//EDIT COURSE ACTION TYPE
export const EDIT_COURSE_START = "EDIT_COURSE_START";
export const EDIT_COURSE_FAILURE = "EDIT_COURSE_FAILURE";
export const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS";

//DELETE COURSE ACTION TYPE
export const DELETE_COURSE_START = "DELETE_COURSE_START";
export const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";

//GET VENDORS DETAILS TYPE
export const GET_VENDOR_DETAILS_START = "GET_VENDOR_DETAILS_START";
export const GET_VENDOR_DETAILS_FAILURE = "GET_VENDOR_DETAILS_FAILURE";
export const GET_VENDOR_DETAILS_SUCCESS = "GET_VENDOR_DETAILS_SUCCESS";

//EDIT VENDOR DETAILS TYPE
export const EDIT_VENDOR_DETAILS_START = "EDIT_VENDOR_DETAILS_START";
export const EDIT_VENDOR_DETAILS_FAILURE = "EDIT_VENDOR_DETAILS_FAILURE";
export const EDIT_VENDOR_DETAILS_SUCCESS = "EDIT_VENDOR_DETAILS_SUCCESS";

//ADD VENDOR ACTION TYPE
export const ADD_VENDOR_START = "ADD_VENDOR_START";
export const ADD_VENDOR_FAILURE = "ADD_VENDOR_FAILURE";
export const ADD_VENDOR_SUCCESS = "ADD_VENDOR_SUCCESS";

//GET Batch LISTS TYPE
export const GET_BATCH_LIST_START = "GET_BATCH_LIST_START";
export const GET_BATCH_LIST_FAILURE = "GET_BATCH_LIST_FAILURE";
export const GET_BATCH_LIST_SUCCESS = "GET_BATCH_LIST_SUCCESS";

//CREATE BATCH ACTION TYPE
export const CREATE_BATCH_START = "CREATE_BATCH_START";
export const CREATE_BATCH_FAILURE = "CREATE_BATCH_FAILURE";
export const CREATE_BATCH_SUCCESS = "CREATE_BATCH_SUCCESS";

//GET COURSE MATERIAL
export const GET_MATERIAL_START = "GET_MATERIAL_START";
export const GET_MATERIAL_FAILURE = "GET_MATERIAL_FAILURE";
export const GET_MATERIAL_SUCCESS = "GET_MATERIAL_SUCCESS";

//ADD FOLDER/SECTION
export const ADD_SECTION_START = "ADD_SECTION_START";
export const ADD_SECTION_FAILURE = "ADD_SECTION_FAILURE";
export const ADD_SECTION_SUCCESS = "ADD_SECTION_SUCCESS";

//GET FOLDER/SECTION
export const GET_SECTION_START = "GET_SECTION_START";
export const GET_SECTION_FAILURE = "GET_SECTION_FAILURE";
export const GET_SECTION_SUCCESS = "GET_SECTION_SUCCESS";

//  SHOW MATERIAL AREAS TYPE
export const ENABLE_ADD_FOLDER = "ENABLE_ADD_FOLDER";
export const ENABLE_ADD_FILE = "ENABLE_ADD_FILE";
export const ENABLE_ADD_VIDEO = "ENABLE_ADD_VIDEO";
export const ENABLE_ADD_CONTENT = "ENABLE_ADD_CONTENT";
export const ENABLE_ADD_ASSIGNMENT = "ENABLE_ADD_ASSIGNMENT";
export const ENABLE_ADD_Q_TEST = "ENABLE_ADD_Q_TEST";
export const ENABLE_ADD_SCORM = "ENABLE_ADD_SCORM";

//  HIDE MATERIAL AREAS TYPE
export const DISABLE_ADD_FOLDER = "DISABLE_ADD_FOLDER";
export const DISABLE_ADD_FILE = "DISABLE_ADD_FILE";
export const DISABLE_ADD_VIDEO = "DISABLE_ADD_VIDEO";
export const DISABLE_ADD_CONTENT = "DISABLE_ADD_CONTENT";
export const DISABLE_ADD_ASSIGNMENT = "DISABLE_ADD_ASSIGNMENT";
export const DISABLE_ADD_CONTENT_Q_TEST = "DISABLE_ADD_CONTENT_Q_TEST";
export const DISABLE_ADD_SCORM = "DISABLE_ADD_SCORM";

//EDIT BATCH ACTION TYPE
export const EDIT_BATCH_START = "EDIT_BATCH_START";
export const EDIT_BATCH_FAILURE = "EDIT_BATCH_FAILURE";
export const EDIT_BATCH_SUCCESS = "EDIT_BATCH_SUCCESS";

//CREATE LIVE CLASS ACTION TYPE
export const CREATE_LIVE_CLASS_START = "CREATE_LIVE_CLASS_START";
export const CREATE_LIVE_CLASS_FAILURE = "CREATE_LIVE_CLASS_FAILURE";
export const CREATE_LIVE_CLASS_SUCCESS = "CREATE_LIVE_CLASS_SUCCESS";

//GET LIVE CLASS LIST ACTION TYPE
export const GET_LIVE_CLASS_LIST_START = "GET_LIVE_CLASS_LIST_START";
export const GET_LIVE_CLASS_LIST_FAILURE = "GET_LIVE_CLASS_LIST_FAILURE";
export const GET_LIVE_CLASS_LIST_SUCCESS = "GET_LIVE_CLASS_LIST_SUCCESS";

//GET LIVE CLASS DETAILS ACTION TYPE
export const GET_LIVE_CLASS_DETAILS_START = "GET_LIVE_CLASS_DETAILS_START";
export const GET_LIVE_CLASS_DETAILS_FAILURE = "GET_LIVE_CLASS_DETAILS_FAILURE";
export const GET_LIVE_CLASS_DETAILS_SUCCESS = "GET_LIVE_CLASS_DETAILS_SUCCESS";

//EDIT LIVE CLASS ACTION TYPE
export const EDIT_LIVE_CLASS_START = "EDIT_LIVE_CLASS_START";
export const EDIT_LIVE_CLASS_FAILURE = "EDIT_LIVE_CLASS_FAILURE";
export const EDIT_LIVE_CLASS_SUCCESS = "EDIT_LIVE_CLASS_SUCCESS";

//DELETE LIVE CLASS ACTION TYPE
export const DELETE_LIVE_CLASS_START = "DELETE_LIVE_CLASS_START";
export const DELETE_LIVE_CLASS_FAILURE = "DELETE_LIVE_CLASS_FAILURE";
export const DELETE_LIVE_CLASS_SUCCESS = "DELETE_LIVE_CLASS_SUCCESS";

//ADD CATEGORY ACTION TYPE
export const ADD_CATEGORY_START = "ADD_CATEGORY_START";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";

//GET CATEGORY ACTION TYPE
export const GET_CATEGORY_START = "GET_CATEGORY_START";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";

//GET CATEGORY LIST ACTION TYPE
export const GET_CATEGORY_LIST_START = "GET_CATEGORY_LIST_START";
export const GET_CATEGORY_LIST_FAILURE = "GET_CATEGORY_LIST_FAILURE";
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS";

//EDIT CATEGORY LIST ACTION TYPE
export const EDIT_CATEGORY_START = "EDIT_CATEGORY_START";
export const EDIT_CATEGORY_FAILURE = "EDIT_CATEGORY_FAILURE";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";

//ADD VIDEO ACTION TYPE
export const ADD_VIDEO_START = "ADD_VIDEO_START";
export const ADD_VIDEO_FAILURE = "ADD_VIDEO_FAILURE";
export const ADD_VIDEO_SUCCESS = "ADD_VIDEO_SUCCESS";

//ADD FILE ACTION TYPE
export const ADD_FILE_START = "ADD_FILE_START";
export const ADD_FILE_FAILURE = "ADD_FILE_FAILURE";
export const ADD_FILE_SUCCESS = "ADD_FILE_SUCCESS";

//EDIT QUESTION BANK ACTION TYPE
export const EDIT_QUESTION_BANK_START = "EDIT_QUESTION_BANK_START";
export const EDIT_QUESTION_BANK_FAILURE = "EDIT_QUESTION_BANK_FAILURE";
export const EDIT_QUESTION_BANK_SUCCESS = "EDIT_QUESTION_BANK_SUCCESS";

//GET QUESTION BANK LIST ACTION TYPE
export const GET_QUESTION_BANK_LIST_START = "GET_QUESTION_BANK_LIST_START";
export const GET_QUESTION_BANK_LIST_FAILURE = "GET_QUESTION_BANK_LIST_FAILURE";
export const GET_QUESTION_BANK_LIST_SUCCESS = "GET_QUESTION_BANK_LIST_SUCCESS";

//GET QUESTION PAPER LIST ACTION TYPE
export const GET_QUESTION_PAPER_LIST_START = "GET_QUESTION_PAPER_LIST_START";
export const GET_QUESTION_PAPER_LIST_FAILURE =
  "GET_QUESTION_PAPER_LIST_FAILURE";
export const GET_QUESTION_PAPER_LIST_SUCCESS =
  "GET_QUESTION_PAPER_LIST_SUCCESS";

//EDIT QUESTION PAPER ACTION TYPE
export const EDIT_QUESTION_PAPER_START = "EDIT_QUESTION_PAPER_START";
export const EDIT_QUESTION_PAPER_FAILURE = "EDIT_QUESTION_PAPER_FAILURE";
export const EDIT_QUESTION_PAPER_SUCCESS = "EDIT_QUESTION_PAPER_SUCCESS";

//GET QUESTION LIST ACTION TYPE
export const GET_QUESTION_LIST_START = "GET_QUESTION_LIST_START";
export const GET_QUESTION_LIST_FAILURE = "GET_QUESTION_LIST_FAILURE";
export const GET_QUESTION_LIST_SUCCESS = "GET_QUESTION_LIST_SUCCESS";

//CREATE QUESTION PAPER ACTION TYPE
export const CREATE_QUESTION_PAPER_START = "CREATE_QUESTION_PAPER_START";
export const CREATE_QUESTION_PAPER_FAILURE = "CREATE_QUESTION_PAPER_FAILURE";
export const CREATE_QUESTION_PAPER_SUCCESS = "CREATE_QUESTION_PAPER_SUCCESS";

//CREATE QUESTION ACTION TYPE
export const CREATE_QUESTION_START = "CREATE_QUESTION_START";
export const CREATE_QUESTION_FAILURE = "CREATE_QUESTION_FAILURE";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";

//CREATE QUESTION BLANK ACTION TYPE
export const CREATE_QUESTION_BLANK_START = "CREATE_QUESTION_BLANK_START";
export const CREATE_QUESTION_BLANK_FAILURE = "CREATE_QUESTION_BLANK_FAILURE";
export const CREATE_QUESTION_BLANK_SUCCESS = "CREATE_QUESTION_BLANK_SUCCESS";

//CREATE QUESTION MCQ ACTION TYPE
export const CREATE_QUESTION_MCQ_START = "CREATE_QUESTION_MCQ_START";
export const CREATE_QUESTION_MCQ_FAILURE = "CREATE_QUESTION_MCQ_FAILURE";
export const CREATE_QUESTION_MCQ_SUCCESS = "CREATE_QUESTION_MCQ_SUCCESS";

//CREATE QUESTION TF ACTION TYPE
export const CREATE_QUESTION_TF_START = "CREATE_QUESTION_TF_START";
export const CREATE_QUESTION_TF_FAILURE = "CREATE_QUESTION_TF_FAILURE";
export const CREATE_QUESTION_TF_SUCCESS = "CREATE_QUESTION_TF_SUCCESS";

//CREATE QUESTION MATCH ACTION TYPE
export const CREATE_QUESTION_MATCH_START = "CREATE_QUESTION_MATCH_START";
export const CREATE_QUESTION_MATCH_FAILURE = "CREATE_QUESTION_MATCH_FAILURE";
export const CREATE_QUESTION_MATCH_SUCCESS = "CREATE_QUESTION_MATCH_SUCCESS";

//CREATE QUESTION ESSAY ACTION TYPE
export const CREATE_QUESTION_ESSAY_START = "CREATE_QUESTION_ESSAY_START";
export const CREATE_QUESTION_ESSAY_FAILURE = "CREATE_QUESTION_ESSAY_FAILURE";
export const CREATE_QUESTION_ESSAY_SUCCESS = "CREATE_QUESTION_ESSAY_SUCCESS";

//ADD CONTENT ACTION TYPE
export const ADD_CONTENT_START = "ADD_CONTENT_START";
export const ADD_CONTENT_FAILURE = "ADD_CONTENT_FAILURE";
export const ADD_CONTENT_SUCCESS = "ADD_CONTENT_SUCCESS";

//ADD ASSIGNMENT ACTION TYPE
export const ADD_ASSIGNMENT_START = "ADD_ASSIGNMENT_START";
export const ADD_ASSIGNMENT_FAILURE = "ADD_ASSIGNMENT_FAILURE";
export const ADD_ASSIGNMENT_SUCCESS = "ADD_ASSIGNMENT_SUCCESS";

//ADD SCORM ACTION TYPE
export const ADD_SCORM_START = "ADD_SCORM_START";
export const ADD_SCORM_FAILURE = "ADD_SCORM_FAILURE";
export const ADD_SCORM_SUCCESS = "ADD_SCORM_SUCCESS";

//START TEST ACTION TYPE
export const START_TEST_START = "START_TEST_START";
export const START_TEST_FAILURE = "START_TEST_FAILURE";
export const START_TEST_SUCCESS = "START_TEST_SUCCESS";

//  SHOW QUESTION TYPE
export const SHOW_MCQ = "SHOW_MCQ";
export const SHOW_ESSAY = "SHOW_ESSAY";
export const SHOW_FILL_BLANK = "SHOW_FILL_BLANK";
export const SHOW_TRUE_FALSE = "SHOW_TRUE_FALSE";
export const SHOW_MATCH = "SHOW_MATCH";

//BULK UPLOAD ACTION TYPE
export const BULK_UPLOAD_START = "BULK_UPLOAD_START";
export const BULK_UPLOAD_FAILURE = "BULK_UPLOAD_FAILURE";
export const BULK_UPLOAD_SUCCESS = "BULK_UPLOAD_SUCCESS";

//DELETE QUESTION ACTION TYPE
export const DELETE_QUESTION_START = "DELETE_QUESTION_START";
export const DELETE_QUESTION_FAILURE = "DELETE_QUESTION_FAILURE";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";

//EDIT QUESTION ACTION TYPE
export const EDIT_QUESTION_START = "EDIT_QUESTION_START";
export const EDIT_QUESTION_FAILURE = "EDIT_QUESTION_FAILURE";
export const EDIT_QUESTION_SUCCESS = "EDIT_QUESTION_SUCCESS";

//DELETE MATERIAL ACTION TYPE
export const DELETE_MATERIAL_START = "DELETE_MATERIAL_START";
export const DELETE_MATERIAL_FAILURE = "DELETE_MATERIAL_FAILURE";
export const DELETE_MATERIAL_SUCCESS = "DELETE_MATERIAL_SUCCESS";

//SET PERMISSION ACTION TYPE
export const SET_PERMISSION_START = "SET_PERMISSION_START";
export const SET_PERMISSION_FAILURE = "SET_PERMISSION_FAILURE";
export const SET_PERMISSION_SUCCESS = "SET_PERMISSION_SUCCESS";

//  SHOW AND HIDE COURSE TYPE
export const SHOW_ALL_COURSE = "SHOW_ALL_COURSE";
export const SHOW_ASSIGNED_COURSE = "SHOW_ASSIGNED_COURSE";
export const SHOW_RECOMMENDED_COURSE = "SHOW_RECOMMENDED_COURSE";
export const HIDE_ALL_COURSE = "HIDE_ALL_COURSE";
export const HIDE_ASSIGNED_COURSE = "HIDE_ASSIGNED_COURSE";
export const HIDE_RECOMMENDED_COURSE = "HIDE_RECOMMENDED_COURSE";

//  GET ASSIGNED COURSES ACTION TYPE
export const GET_ASSIGNED_COURSES_START = "GET_ASSIGNED_COURSES_START";
export const GET_ASSIGNED_COURSES_FAILURE = "GET_ASSIGNED_COURSES_FAILURE";
export const GET_ASSIGNED_COURSES_SUCCESS = "GET_ASSIGNED_COURSES_SUCCESS";

//  GET ASSIGNED QUESTION PAPER
export const GET_ASSIGNED_PAPER_START = "GET_ASSIGNED_PAPER_START";
export const GET_ASSIGNED_PAPER_FAILURE = "GET_ASSIGNED_PAPER_FAILURE";
export const GET_ASSIGNED_PAPER_SUCCESS = "GET_ASSIGNED_PAPER_SUCCESS";

//  GET ALL COURSES ACTION TYPE
export const GET_ALL_COURSES_START = "GET_ALL_COURSES_START";
export const GET_ALL_COURSES_FAILURE = "GET_ALL_COURSES_FAILURE";
export const GET_ALL_COURSES_SUCCESS = "GET_ALL_COURSES_SUCCESS";

//  GET MATERIAL BY SECTION ACTION TYPE
export const GET_MATERIAL_BY_SECTION_START = "GET_MATERIAL_BY_SECTION_START";
export const GET_MATERIAL_BY_SECTION_FAILURE =
  "GET_MATERIAL_BY_SECTION_FAILURE";
export const GET_MATERIAL_BY_SECTION_SUCCESS =
  "GET_MATERIAL_BY_SECTION_SUCCESS";

//  GET MATERIAL BY SECTION ACTION TYPE
export const ASSIGN_COURSE_START = "ASSIGN_COURSE_START";
export const ASSIGN_COURSE_FAILURE = "ASSIGN_COURSE_FAILURE";
export const ASSIGN_COURSE_SUCCESS = "ASSIGN_COURSE_SUCCESS";

// GAMIFICATION ACTION TYPE
export const GAMIFICATION_START = "GAMIFICATION_START";
export const GAMIFICATION_FAILURE = "GAMIFICATION_FAILURE";
export const GAMIFICATION_SUCCESS = "GAMIFICATION_SUCCESS";

// EDIT GAMIFICATION ACTION TYPE
export const EDIT_GAMIFICATION_START = "EDIT_GAMIFICATION_START";
export const EDIT_GAMIFICATION_FAILURE = "EDIT_GAMIFICATION_FAILURE";
export const EDIT_GAMIFICATION_SUCCESS = "EDIT_GAMIFICATION_SUCCESS";

// DELETE GAMIFICATION ACTION TYPE
export const DELETE_GAMIFICATION_START = "DELETE_GAMIFICATION_START";
export const DELETE_GAMIFICATION_FAILURE = "DELETE_GAMIFICATION_FAILURE";
export const DELETE_GAMIFICATION_SUCCESS = "DELETE_GAMIFICATION_SUCCESS";

// ADD QTEST ACTION TYPE
export const ADD_QTEST_START = "ADD_QTEST_START";
export const ADD_QTEST_FAILURE = "ADD_QTEST_FAILURE";
export const ADD_QTEST_SUCCESS = "ADD_QTEST_SUCCESS";

// SET GAMIFICATION ACTION TYPE
export const SET_GAMIFICATION_START = "SET_GAMIFICATION_START";
export const SET_GAMIFICATION_FAILURE = "SET_GAMIFICATION_FAILURE";
export const SET_GAMIFICATION_SUCCESS = "SET_GAMIFICATION_SUCCESS";

// GET QUESTION PAPER BY ID's
export const GET_QUESTIONS_START = "GET_QUESTIONS_START";
export const GET_QUESTIONS_FAILURE = "GET_QUESTIONS_FAILURE";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";

// CREATE TOPIC IN COURSE
export const ADD_TOPIC_START = "ADD_TOPIC_START";
export const ADD_TOPIC_FAILURE = "ADD_TOPIC_FAILURE";
export const ADD_TOPIC_SUCCESS = "ADD_TOPIC_SUCCESS";

// CREATE SESSION IN COURSE
export const ADD_SESSION_START = "ADD_SESSION_START";
export const ADD_SESSION_FAILURE = "ADD_SESSION_FAILURE";
export const ADD_SESSION_SUCCESS = "ADD_SESSION_SUCCESS";

// ADD ARTIFACTS IN SESSION OF A COURSE TYPES
export const ADD_ARTIFACTS_START = "ADD_ARTIFACTS_START";
export const ADD_ARTIFACTS_FAILURE = "ADD_ARTIFACTS_FAILURE";
export const ADD_ARTIFACTS_SUCCESS = "ADD_ARTIFACTS_SUCCESS";

// GET COURSE TOPIC LIST
export const GET_COURSE_TOPIC_LIST_START = "GET_COURSE_TOPIC_LIST_START";
export const GET_COURSE_TOPIC_LIST_FAILURE = "GET_COURSE_TOPIC_LIST_FAILURE";
export const GET_COURSE_TOPIC_LIST_SUCCESS = "GET_COURSE_TOPIC_LIST_SUCCESS";

// GET ALL SESSION BY TOPIC
export const GET_ALL_SESSION_BY_TOPIC_START = "GET_ALL_SESSION_BY_TOPIC_START";
export const GET_ALL_SESSION_BY_TOPIC_FAILURE =
  "GET_ALL_SESSION_BY_TOPIC_FAILURE";
export const GET_ALL_SESSION_BY_TOPIC_SUCCESS =
  "GET_ALL_SESSION_BY_TOPIC_SUCCESS";

// GET LEARNER STATUS
export const GET_LEARNER_STATUS_START = "GET_LEARNER_STATUS_START";
export const GET_LEARNER_STATUS_SUCCESS = "GET_LEARNER_STATUS_SUCCESS";
export const GET_LEARNER_STATUS_FAILURE = "GET_LEARNER_STATUS_FAILURE";

// GET ACTIVE COURSE STATUS
export const GET_ACTIVE_COURSE_STATUS_START = "GET_ACTIVE_COURSE_STATUS_START";
export const GET_ACTIVE_COURSE_STATUS_SUCCESS =
  "GET_ACTIVE_COURSE_STATUS_SUCCESS";
export const GET_ACTIVE_COURSE_STATUS_FAILURE =
  "GET_ACTIVE_COURSE_STATUS_FAILURE";

// GET COMPLETED COURSE STATUS
export const GET_COURSE_COMPLETED_STATUS_START =
  "GET_COURSE_COMPLETED_STATUS_START";
export const GET_COURSE_COMPLETED_STATUS_SUCCESS =
  "GET_COURSE_COMPLETED_STATUS_SUCCESS";
export const GET_COURSE_COMPLETED_STATUS_FAILURE =
  "GET_COURSE_COMPLETED_STATUS_FAILURE";

// User Enroll Cources
export const ADD_USER_ENROLL_COURCE_START = "ADD_USER_ENROLL_COURCE_START";
export const ADD_USER_ENROLL_COURCE_FAILURE = "ADD_USER_ENROLL_COURCE_FAILURE";
export const ADD_USER_ENROLL_COURCE_SUCCESS = "ADD_USER_ENROLL_COURCE_SUCCESS";

//GET QUESTIONS
export const GET_QUESTION_DETAILS_START = "GET_QUESTION_DETAILS_START";
export const GET_QUESTION_DETAILS_FAILURE = "GET_QUESTION_DETAILS_FAILURE";
export const GET_QUESTION_DETAILS_SUCCESS = "GET_QUESTION_DETAILS_SUCCESS";

//DELETE VENDOR ACTION TYPE
export const DELETE_VENDOR_START = "DELETE_VENDOR_START";
export const DELETE_VENDOR_FAILURE = "DELETE_VENDOR_FAILURE";
export const DELETE_VENDOR_SUCCESS = "DELETE_VENDOR_SUCCESS";

//SET FAVORITE ACTION TYPE
export const SET_FAVORITE_START = "SET_FAVORITE_START";
export const SET_FAVORITE_FAILURE = "SET_FAVORITE_FAILURE";
export const SET_FAVORITE_SUCCESS = "SET_FAVORITE_SUCCESS";

//POST SUBMIT TEST TYPE
export const SUBMIT_TEST_START = "SUBMIT_TEST_START";
export const SUBMIT_TEST_FAILURE = "SUBMIT_TEST_FAILURE";
export const SUBMIT_TEST_SUCCESS = "SUBMIT_TEST_SUCCESS";

//GET TEST RESULT BY QUESTION PAPER LIST
export const GET_TEST_RESULT_BY_QUESTION_PAPER_LIST_START =
  "GET_TEST_RESULT_BY_QUESTION_PAPER_LIST_START";
export const GET_TEST_RESULT_BY_QUESTION_PAPER_LIST_FAILURE =
  "GET_TEST_RESULT_BY_QUESTION_PAPER_LIST_FAILURE";
export const GET_TEST_RESULT_BY_QUESTION_PAPER_LIST_SUCCESS =
  "GET_TEST_RESULT_BY_QUESTION_PAPER_LIST_SUCCESS";

// DOWNLOAD COURSE SAMPLE START TYPES

export const DOWNLOAD_COURSE_SAMPLE_START = "DOWNLOAD_COURSE_SAMPLE_START";
export const DOWNLOAD_COURSE_SAMPLE_FAILURE = "DOWNLOAD_COURSE_SAMPLE_FAILURE";
export const DOWNLOAD_COURSE_SAMPLE_SUCCESS = "DOWNLOAD_COURSE_SAMPLE_SUCCESS";

// UPLOAD COURSE EXCEL START TYPES

export const UPLOAD_COURSE_EXCEL_START = "UPLOAD_COURSE_EXCEL_START";
export const UPLOAD_COURSE_EXCEL_FAILURE = "UPLOAD_COURSE_EXCEL_FAILURE";
export const UPLOAD_COURSE_EXCEL_SUCCESS = "UPLOAD_COURSE_EXCEL_SUCCESS";

//  GET MATERIAL BY SESSION ACTION TYPE
export const GET_MATERIAL_BY_SESSION_START = "GET_MATERIAL_BY_SESSION_START";
export const GET_MATERIAL_BY_SESSION_FAILURE =
  "GET_MATERIAL_BY_SESSION_FAILURE";
export const GET_MATERIAL_BY_SESSION_SUCCESS =
  "GET_MATERIAL_BY_SESSION_SUCCESS";

//  GET MATERIAL BY SESSION ACTION TYPE
export const GET_FIRST_MATERIAL_BY_COURSE_START =
  "GET_FIRST_MATERIAL_BY_COURSE_START";
export const GET_FIRST_MATERIAL_BY_COURSE_FAILURE =
  "GET_FIRST_MATERIAL_BY_COURSE_FAILURE";
export const GET_FIRST_MATERIAL_BY_COURSE_SUCCESS =
  "GET_FIRST_MATERIAL_BY_COURSE_SUCCESS";

// GET START TEST BY COURSE
export const START_TEST_BY_COURSE_START = "START_TEST_BY_COURSE_START";
export const START_TEST_BY_COURSE_FAILURE = "START_TEST_BY_COURSE_FAILURE";
export const START_TEST_BY_COURSE_SUCCESS = "START_TEST_BY_COURSE_SUCCESS";

// POST START TEST BY COURSE
export const COURSE_SUBMIT_TEST_START = "COURSE_SUBMIT_TEST_START";
export const COURSE_SUBMIT_TEST_FAILURE = "COURSE_SUBMIT_TEST_FAILURE";
export const COURSE_SUBMIT_TEST_SUCCESS = "COURSE_SUBMIT_TEST_SUCCESS";

// GET TEST RESULTS BY COURSE
export const GET_TEST_RESULT_BY_COURSE_START =
  "GET_TEST_RESULT_BY_COURSE_START";
export const GET_TEST_RESULT_BY_COURSE_FAILURE =
  "GET_TEST_RESULT_BY_COURSE_FAILURE";
export const GET_TEST_RESULT_BY_COURSE_SUCCESS =
  "GET_TEST_RESULT_BY_COURSE_SUCCESS";

// GET CURRENT TEST RESULT
export const GET_CURRENT_TEST_RESULT_START = "GET_CURRENT_TEST_RESULT_START";
export const GET_CURRENT_TEST_RESULT_FAILURE =
  "GET_CURRENT_TEST_RESULT_FAILURE";
export const GET_CURRENT_TEST_RESULT_SUCCESS =
  "GET_CURRENT_TEST_RESULT_SUCCESS";

//  GET MATERIAL BY TOPIC ACTION TYPE
export const GET_MATERIAL_BY_TOPIC_START = "GET_MATERIAL_BY_TOPIC_START";
export const GET_MATERIAL_BY_TOPIC_FAILURE = "GET_MATERIAL_BY_TOPIC_FAILURE";
export const GET_MATERIAL_BY_TOPIC_SUCCESS = "GET_MATERIAL_BY_TOPIC_SUCCESS";

//  GET NESTED CATEGORY ACTION TYPE
export const GET_NESTED_CATEGORY_START = "GET_NESTED_CATEGORY_START";
export const GET_NESTED_CATEGORY_FAILURE = "GET_NESTED_CATEGORY_FAILURE";
export const GET_NESTED_CATEGORY_SUCCESS = "GET_NESTED_CATEGORY_SUCCESS";

//  GET Learning Path By Category  ACTION TYPE
export const GET_NESTED_LEARNING_PATH_BY_CATEGORY_START =
  "GET_NESTED_LEARNING_PATH_BY_CATEGORY_START";
export const GET_NESTED_LEARNING_PATH_BY_CATEGORY_FAILURE =
  "GET_NESTED_LEARNING_PATH_BY_CATEGORY_FAILURE";
export const GET_NESTED_LEARNING_PATH_BY_CATEGORY_SUCCESS =
  "GET_NESTED_LEARNING_PATH_BY_CATEGORY_SUCCESS";

//GET POPULAR COURSES ACTION TYPE
export const GET_POPULAR_COURSES_LIST_START = "GET_POPULAR_COURSES_LIST_START";
export const GET_POPULAR_COURSES_LIST_FAILURE =
  "GET_POPULAR_COURSES_LIST_FAILURE";
export const GET_POPULAR_COURSES_LIST_SUCCESS =
  "GET_POPULAR_COURSES_LIST_SUCCESS";

// GET COURSE COUNT ACTION TYPE
export const GET_COURSE_COUNT_START = "GET_COURSE_COUNT_START";
export const GET_COURSE_COUNT_FAILURE = "GET_COURSE_COUNT_FAILURE";
export const GET_COURSE_COUNT_SUCCESS = "GET_COURSE_COUNT_SUCCESS";

// GET ALL LEARNING PATH ACTION TYPE
export const GET_LEARNING_PATH_START = "GET_LEARNING_PATH_START";
export const GET_LEARNING_PATH_FAILURE = "GET_LEARNING_PATH_FAILURE";
export const GET_LEARNING_PATH_SUCCESS = "GET_LEARNING_PATH_SUCCESS";

// GET ALL TEST RESULTS FOR ADMIN ACTION TYPE
export const GET_ALL_TEST_RESULTS_FOR_ADMIN_START =
  "GET_ALL_TEST_RESULTS_FOR_ADMIN_START";
export const GET_ALL_TEST_RESULTS_FOR_ADMIN_FAILURE =
  "GET_ALL_TEST_RESULTS_FOR_ADMIN_FAILURE";
export const GET_ALL_TEST_RESULTS_FOR_ADMIN_SUCCESS =
  "GET_ALL_TEST_RESULTS_FOR_ADMIN_SUCCESS";

// GET ADD REMARKS BY ADMIN ACTION TYPE
export const ADD_REMARKS_BY_ADMIN_START = "ADD_REMARKS_BY_ADMIN_START";
export const ADD_REMARKS_BY_ADMIN_FAILURE = "ADD_REMARKS_BY_ADMIN_FAILURE";
export const ADD_REMARKS_BY_ADMIN_SUCCESS = "ADD_REMARKS_BY_ADMIN_SUCCESS";

// DOWNLOAD COURSE UPLOAD TEMPLATE ACTION TYPE
export const DOWNLOAD_COURSE_UPLOAD_TEMPLATE_START =
  "DOWNLOAD_COURSE_UPLOAD_TEMPLATE_START";
export const DOWNLOAD_COURSE_UPLOAD_TEMPLATE_FAILURE =
  "DOWNLOAD_COURSE_UPLOAD_TEMPLATE_FAILURE";
export const DOWNLOAD_COURSE_UPLOAD_TEMPLATE_SUCCESS =
  "DOWNLOAD_COURSE_UPLOAD_TEMPLATE_SUCCESS";

// UPLOAD QUESTIONS EXCEL FILE ACTION TYPE
export const UPLOAD_QUESTIONS_FILE_START = "UPLOAD_QUESTIONS_FILE_START";
export const UPLOAD_QUESTIONS_FILE_FAILURE = "UPLOAD_QUESTIONS_FILE_FAILURE";
export const UPLOAD_QUESTIONS_FILE_SUCCESS = "UPLOAD_QUESTIONS_FILE_SUCCESS";

//  GET COURSES By Category  ACTION TYPE
export const GET_COURSES_BY_CATEGORY_START = "GET_COURSES_BY_CATEGORY_START";
export const GET_COURSES_BY_CATEGORY_FAILURE =
  "GET_COURSES_BY_CATEGORY_FAILURE";
export const GET_COURSES_BY_CATEGORY_SUCCESS =
  "GET_COURSES_BY_CATEGORY_SUCCESS";


// UPLOAD QUESTIONS EXCEL FILE ACTION TYPE
export const GET_COURSE_DETAILS_START = "GET_COURSE_DETAILS_START";
export const GET_COURSE_DETAILS_FAILURE = "GET_COURSE_DETAILS_FAILURE";
export const GET_COURSE_DETAILS_SUCCESS = "GET_COURSE_DETAILS_SUCCESS";

//JOIN COURSE
export const JOIN_COURSE_START = "JOIN_COURSE_START";
export const JOIN_COURSE_FAILURE = "JOIN_COURSE_FAILURE";
export const JOIN_COURSE_SUCCESS = "JOIN_COURSE_SUCCESS";

// USER REGISTER
export const REGISTER_START = "REGISTER_START";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

// ADD COURSE TO WISH LIST
export const ADD_COURSE_TO_WISH_LIST_START = "ADD_COURSE_TO_WISH_LIST_START";
export const ADD_COURSE_TO_WISH_LIST_FAILURE = "ADD_COURSE_TO_WISH_LIST_FAILURE";
export const ADD_COURSE_TO_WISH_LIST_SUCCESS = "ADD_COURSE_TO_WISH_LIST_SUCCESS";

// GET USER COURSE WISH LIST
export const GET_USER_COURSE_WISH_LIST_START = "GET_USER_COURSE_WISH_LIST_START";
export const GET_USER_COURSE_WISH_LIST_FAILURE = "GET_USER_COURSE_WISH_LIST_FAILURE";
export const GET_USER_COURSE_WISH_LIST_SUCCESS = "GET_USER_COURSE_WISH_LIST_SUCCESS";

// ADD BATCH 
export const ASSIGN_BATCH_START = "ASSIGN_BATCH_START";
export const ASSIGN_BATCH_FAILURE = "ASSIGN_BATCH_FAILURE";
export const ASSIGN_BATCH_SUCCESS = "ASSIGN_BATCH_SUCCESS";


// GET BACTH LIST BY ID
export const GET_BATCH_LIST_BY_ID_START = "GET_BATCH_LIST_BY_ID_START";
export const GET_BATCH_LIST_BY_ID_FAILURE = "GET_BATCH_LIST_BY_ID_FAILURE";
export const GET_BATCH_LIST_BY_ID_SUCCESS = "GET_BATCH_LIST_BY_ID_SUCCESS";


// GET USERS FROM BATCH
export const GET_USERS_FROM_BATCH_START = "GET_USERS_FROM_BATCH_START";
export const GET_USERS_FROM_BATCH_FAILURE = "GET_USERS_FROM_BATCH_FAILURE";
export const GET_USERS_FROM_BATCH_SUCCESS = "GET_USERS_FROM_BATCH_SUCCESS";

// GET ALL MY BATCHES
export const GET_MY_ALL_BATCHES_START = "GET_MY_ALL_BATCHES_START";
export const GET_MY_ALL_BATCHES_FAILURE = "GET_MY_ALL_BATCHES_FAILURE";
export const GET_MY_ALL_BATCHES_SUCCESS = "GET_MY_ALL_BATCHES_SUCCESS";

// DELETE TOPIC
export const DELETE_TOPIC_START = "DELETE_TOPIC_START";
export const DELETE_TOPIC_FAILURE = "DELETE_TOPIC_FAILURE";
export const DELETE_TOPIC_SUCCESS = "DELETE_TOPIC_SUCCESS";